### ISSUE TITLE
Are there any more example fully rigged characters like lambert.mb? For example, woman_base rigged? Otherwise, what's the process to build one?

### ISSUE THREAD

**Issue by strazto** [dingdio/witcher3-maya-animation#2]

**Comment by dingdio** [comment]
I've added shani.mb here:
https://mega.nz/folder/fZpiXZzS#xd3mWgqtAQND0UI90KWk7Q
I'll do a full tutorial of importing character entities once I release a new version of this tool. But for now it's probably not worth trying to do it. Shani uses the same skeleton as all other women in the game.

Here is a image of the current progress of adding entity import features:
https://i.imgur.com/qp2P3Kh.jpg
You can see you'll be able to select appearance and turn on the importing of all face poses.
The "Fbx Depo Path" will hold converted fbx files that can be imported into Maya with their skeleton.

The general process to automatically create an character would be
- Open Wolven-kit and find shani.w2ent
- Export shani.w2ent.json
- Some process that will get all the fbx/rig files into "Fbx Depo Path" and make sure they're readable by Maya. Right now I'm using a script I wrote to do all this.
- Import shani.w2ent.json in Maya, this will read and combine all items and rigs in the "Fbx Depo Path" into a full character.

Would use the same process to import things like the items in cutscenes.
You can manually create the json yourself by editing existing json and just changing the paths to some other object in the "Fbx Depo Path".

**Comment by strazto** [comment]
thank you - The shani.mb should actually meet my needs :)
